### PR TITLE
Feature/readme update

### PR DESCRIPTION
**Pull request by theendsofinvention**
I've added the documentation made by Entropy to the repository's README file.

The output can be previewed at:
https://github.com/132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi/tree/feature/readme-update

Provided you both approve, I'll squash-merge this PR into develop.

### CODE REVIEW

**Comment by theendsofinvention** [comment]
Guys ?

**Comment by 132nd-Entropy** [comment]
awesomeness!

**Comment by theendsofinvention** [comment]
Thanks ! I'm waiting on the review from @132ndNeck before merging then.

**Comment by theendsofinvention** [comment]
@132ndNeck, does this look good to you ?

**Review by 132nd-Entropy — APPROVED** [review]

**Pull request merged**
